# -*- coding: utf-8 -*-
"""download_forex_data.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kIGNmkb8Ct4Pe_qsGty0gKGHE89IAda
"""

!pip install yfinance

import yfinance as yf

# Download historical data for EUR/USD from Yahoo Finance
symbol = 'EURUSD=X'  # EUR/USD currency pair
data = yf.download(symbol, start="2010-01-01", end="2025-01-01", interval="1d")  # Changed interval to 1d

# Save the data to CSV
data.to_csv('forex_data.csv')

print("Forex data saved as forex_data.csv")