# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np

# Generate Fake Forex Data (100,000 samples)
np.random.seed(42)
dates = pd.date_range(start="2023-01-01", periods=100000, freq="H")

# Generate 100,000 price values
prices = np.random.randn(100000).cumsum() + 100  # Simulated price movements

# Create DataFrame
forex_data = pd.DataFrame({
    "Date": dates,
    "Open": prices + np.random.randn(100000),
    "High": prices + np.random.rand(100000) * 2,
    "Low": prices - np.random.rand(100000) * 2,
    "Close": prices,
    "Volume": np.random.randint(100, 1000, size=(100000,))
})

# Save to CSV
forex_data.to_csv("forex_data.csv", index=False)
print("Forex data saved as forex_data.csv with 100,000 records")